name: Build OpenWrt

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OpenWrt build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext unzip zlib1g-dev file
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build OpenWrt
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Archive build artifacts
      if: success()
      run: |
        cd openwrt/bin/targets
        tar -czvf openwrt-build.tar.gz *
      shell: bash

    - name: Upload release to GitHub
      if: success()
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: openwrt/bin/targets/openwrt-build.tar.gz
        asset_name: openwrt-build.tar.gz
        asset_content_type: application/gzip

    - name: Create GitHub Release
      if: success()
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: OpenWrt Build ${{ github.run_number }}
        draft: false
        prerelease: false
