name: Build OpenWrt Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OpenWrt Image Builder environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext unzip zlib1g-dev file wget
        wget https://downloads.openwrt.org/releases/22.03.0/targets/x86/64/openwrt-imagebuilder-22.03.0-x86-64.Linux-x86_64.tar.xz
        tar -xf openwrt-imagebuilder-22.03.0-x86-64.Linux-x86_64.tar.xz

    - name: Build OpenWrt Image
      run: |
        cd openwrt-imagebuilder-22.03.0-x86-64.Linux-x86_64
        make image PROFILE=generic PACKAGES="luci luci-app-opkg"

    - name: Archive build artifacts
      if: success()
      run: |
        cd openwrt-imagebuilder-22.03.0-x86-64.Linux-x86_64/bin/targets/x86/64
        tar -czvf openwrt-image.tar.gz *
      shell: bash

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: OpenWrt Image Build ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload release to GitHub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: openwrt-imagebuilder-22.03.0-x86-64.Linux-x86_64/bin/targets/x86/64/openwrt-image.tar.gz
        asset_name: openwrt-image.tar.gz
        asset_content_type: application/gzip
