name: Build AniWRT

on:
  workflow_dispatch:
    inputs:
      resources:
        description: 'Pilih versi OpenWrt atau ImmortalWRT'
        required: true
        type: string
        default: openwrt:23.05.4
      rootfs_size:
        description: 'ROOTFS_PARTSIZE dalam MB'
        required: true
        type: number
        default: 256

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Image Builder
      id: setup
      run: |
        RESOURCES="${{ github.event.inputs.resources }}"
        ROOTFS_SIZE="${{ github.event.inputs.rootfs_size }}"

        # Pisahkan VERSION menjadi version1 dan version2
        IFS=':' read -r base version <<< "$RESOURCES"

        echo "Base: $base"
        echo "Version: $version"

        # Mapping version1 dan version2 ke URL
        wget https://downloads.$base.org/releases/$version/targets/armsr/armv8/$base-imagebuilder-$version-armsr-armv8.Linux-x86_64.tar.xz -O imagebuilder.tar.xz
        tar -xf imagebuilder.tar.xz
        ls

    - name: Build Image
      run: |
        make image PROFILE=generic ROOTFS_PARTSIZE=$ROOTFS_SIZE

    - name: Upload image to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: path/to/your/image.img
        asset_name: your-image-name.img
        asset_content_type: application/octet-stream
